<?php
namespace applications\main;


use applications\main\entities\Notification;
use applications\main\entities\Widget;
use applications\meta\entities\Meta;
use applications\pages\entities\Pagina;
use core\abstracts\Application;
use core\abstracts\FrontendApplication;
use core\Model;
use core\services\Response;

class MainApplication extends Application {
    static function init($n)
    {
        parent::init($n); // TODO: Change the autogenerated stub

        Response::addVariable([
            "notifications" => Notification::query()->setOrderBy("readed","DESC")->getAll()
        ]);
    }


    static function getFrontendApplication()
    {
        return null;
    }


    static function getBackendApplication()
    {
        // TODO: Implement getBackendApplication() method.
        return MainBackend::class;
    }

    static function getEntityClass()
    {
        return Widget::class;
    }

    static function install()
    {

        return [
            Widget::class,
            Notification::class
        ];
    }


}