<?php
namespace applications\main;

use applications\main\entities\Notification;
use backend\BackendTemplate;
use core\abstracts\BackendApplication;

class NotificationsApplication extends BackendApplication{
    static function getEntityClass()
    {
        return Notification::class; // TODO: Change the autogenerated stub
    }

    static function getApplication()
    {
        return MainApplication::class; // TODO: Change the autogenerated stub
    }

    static function actionList($params = [])
    {

        return parent::actionList($params); // TODO: Change the autogenerated stub
    }
}