<?php

namespace applications\anagraficaimmobili\entities;


use core\db\Field;
use core\Model;
use core\services\Db;

use applications\anagraficaimmobili\entities\Condominio;

class Edificio extends Model{

    static function schema()
    {
        return array_merge([
            "id"    =>  Field::primaryIndex(), //Come lo setto auto increment?
            "idCondominio"  =>  Field::int()->editable()->setLabel("Condominio")->setTemplate("select")->setTemplateVar(Condominio::getForSelect("denominazione","id")),

            "codice"  =>  Field::varchar(30)->editable()->setPlaceholder("Codice univoco edificio")->setFieldsize("small")->setLabel("Codice Edificio")->setMaxlength(30)->required(),
            "nomeEdificio"  =>  Field::varchar(255)->editable()->setLabel("Nome Edificio")->setFieldsize("medium"),

            "indirizzo"  =>  Field::varchar(255)->editable(),
            "civico"  =>  Field::varchar(20)->editable()->setFieldsize("small"),
            
            //campi da definire per utilità a livello di edificio


            "attivo"  =>  Field::int()->inlist(false),



        ],parent::schema());
    }

    function displayValue($key)
    {
        switch ($key){
            case "idCondominio":
                if( $this->idCondominio ) {
                    $f = Condominio::findById($this->idCondominio);
                    if ($f) {
                        return $f->denominazione;
                    }
                }
                break;
            case "Condominio_Edificio":
                if( $this->idCondominio ) {
                    $f = Condominio::findById($this->idCondominio);
                    if ($f) {
                        return $f->denominazione . " - " . $this->nomeEdificio;
                    }
                }else{
                    $this->nomeEdificio;
                }
                break;

        }
        return parent::displayValue($key); // TODO: Change the autogenerated stub
    }

}