<?php

namespace core\services;

use core\abstracts\Application;
use core\Config;
use core\template\BaseTemplate;


class ApplicationsService extends \core\abstracts\Service {
    static function getName()
    {
        return "applications";
    }

    static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub


        if( count(self::$config) > 0 ){
            foreach (self::$config as $key => $item) {
                /**
                 * @var $item Application
                 */
                $item::init( $key );
            }
        }
    }


    /**
     * @return Application[]
     */
    static function getAll(){
        return self::$config;
    }
}