<?php
namespace applications\settings\entities;

use core\db\Field;

class Setting extends \core\Model{
    static function getTable()
    {
        return "settings"; // TODO: Change the autogenerated stub
    }

    static function useCache()
    {
        return false;
    }
    static function schema()
    {
        return [
            "id"=>Field::primaryIndex(),
            "setting_key"   =>  Field::varchar("30")->editable()->index(),
            "setting_group" =>  Field::varchar(30)->setDefault('"system"')->editable(),
            "setting_value"=>Field::text()->editable()->setTemplate("textarea"),
           
        ]; // TODO: Change the autogenerated stub
    }


    static function exists($k){
        $s = self::fromKey($k);
        return isset($s->id);
    }
    static function fromKey( $k ){
        $s = Setting::query()->where('setting_key="'.$k.'"')->getOne();
        if(!$s){
            $s = new Setting(["setting_key"=>$k]);
            $s->setting_value = "";
        }
        return $s;
    }

    static function getValueOf($k,$default = ""){
        $s = self::fromKey($k);
        
        return !empty($s->setting_value) ? $s->setting_value : $default;
    }


}