<?php
namespace core\services;

use core\abstracts\Service;
use core\db\DbPdo;

class Db extends Service {

    /**
     * @var DbPdo
     */
    static $connection = null;

    static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub


        try {
            $host   =   self::$config['host'];
            $db     =   self::$config['db'];
            $user   =   self::$config['user'];
            $password=  self::$config['password'];

            // stringa di connessione al DBMS
            self::$connection = new DbPdo("mysql:host=$host;dbname=$db", $user, $password);

            $r = self::$connection->query("SHOW DATABASES LIKE 'dbname';");

        }
        catch(\PDOException $e)
        {


            header("Location: /install");
            // notifica in caso di errore nel tentativo di connessione
            echo $e->getMessage();
        }
    }

    static function getName()
    {
        return "db";
    }


    /**
     * @return DbPdo
     */
    static function getInstance(){
        return self::$connection;
    }

    static function tableExists( $table ){
        $query = "SHOW TABLES LIKE '".$table."';";
        $r = static::getInstance()->query($query)->fetchAll();
        return count($r) > 0;
    }




}