<?php
namespace core\services;
use applications\login\LoginApplication;
use core\abstracts\Service;
use core\template\BaseTemplate;

class SessionService extends Service {
    static $scadenza = 2592000;

    static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        session_start();
    }

    static function getName()
    {
        return "session";
    }

    static function exists( $varname ){

        try {
            return isset($_SESSION[$varname]);
        }catch (\Exception $e){
            var_dump($varname);
            exit;
        }
    }

    static function set( $varname, $value ){
        $_SESSION[$varname] = $value;
    }
    static function get( $varname ){

        return static::exists($varname) ? $_SESSION[$varname] : null;
    }
    static function delete( $varname){
        if( self::exists($varname)){
            unset($_SESSION[$varname]);
        }
    }


    static function getCookie( $varname ){
        if($varname!=""){
            if(isset($_COOKIE[$varname]) && $_COOKIE[$varname]!="")
                return $_COOKIE[$varname];
        }
        return false;
    }
    static function setCookie( $varname, $varvalue ){
        if($varname!=""){
            setcookie($varname,$varvalue,time() + SessionService::$scadenza);
            return SessionService::$scadenza;
        }
        return false;
    }
    static function delCookie( $varname ){
        if($varname!=""){
            setcookie($varname,"",time() - 3600);
            return true;
        }
        return false;
    }

}
