<?php

namespace frontend\consorzioleonardo\applications\progetti;

use core\abstracts\Application;
use core\services\Response;
use frontend\consorzioleonardo\applications\imprese\entities\Impresa;
use frontend\consorzioleonardo\applications\progetti\entities\AziendaProgetto;
use frontend\consorzioleonardo\applications\progetti\entities\Progetto;


class ProgettiApplication extends Application{
    static function getFrontendApplication()
    {
        return null;
    }

    static function getBackendApplication()
    {
        return ProgettiBackend::class;
    }

    static function getEntityClass()
    {
        return Progetto::class;
    }

    static function install()
    {
        return [
            Progetto::class,
            AziendaProgetto::class
        ];
    }

    static function init($n)
    {
        parent::init($n); // TODO: Change the autogenerated stub


        parent::init($n); // TODO: Change the autogenerated stub
        Response::addVariable([
            "menu"  =>  [
                "gestionecontenuti" => [[
                    "icon"  =>  "database",
                    "label" =>  "Progetti",
                    "children"  =>  [
                        ["label" => "Lista", "href" =>  "/backend/progetti/lista"],
                        ["label" => "Aggiungi","href" =>  "/backend/progetti/aggiungi"]
                    ]
                ]]
            ]
        ]);

    }


}