<?php

namespace applications\faq;

use applications\faq\entities\FaqAnswer;
use core\abstracts\BackendApplication;

class FaqAnswerBackend extends BackendApplication{


    public static function getApplication()
    {
        return FaqApplication::class;
    }

    public static function getEntityClass()
    {
        return FaqAnswer::class; // TODO: Change the autogenerated stub
    }

}