<?php
namespace applications\faq;

use applications\faq\entities\Faq;
use applications\pages\PagesFrontend;
use backend\Menu;
use core\abstracts\Application;
use core\abstracts\BackendApplication;
use core\abstracts\FrontendApplication;
use core\Events;
use core\Model;
use core\services\Response;
use core\services\RouterService;
use Stripe\Event;

class FaqApplication extends Application{
    static function init($n)
    {
        parent::init($n); // TODO: Change the autogenerated stub


        $menu = new Menu("FAQ","question-circle");

        $menu->addItem( "Lista", RouterService::getRoute(Faq::class.".list"));

        $backend = Response::getBackendTemplate();
        $backend::addMenu($menu);

        RouterService::addRoutesPrefixed(FaqAnswerBackend::declareRoutes(),"/backend/faq/domande/");


        Events::add(Events::ROUTER_AFTER_DISPATCH,function ($response,$route,$params){




            if( $route->callback[0] == PagesFrontend::class ) {



                $pagina = $response[1]["content"];

                if( $pagina && $faq = Faq::query()
                    ->where("id_pagina=".$pagina->id)->getOne() ){



                    $faq->expand();

                    $response[1]["faq"]=$faq;
                    $response[0] = "faq/default";
                }

            }

            return $response;
        });
    }


    static function getFrontendApplication()
    {
       return null;
    }

    static function getBackendApplication()
    {
        return FaqBackend::class;
    }

    static function getEntityClass()
    {
        return Faq::class;
    }
}
