<?php

namespace applications\faq;

use applications\faq\entities\Faq;
use backend\BackendTemplate;
use core\abstracts\BackendApplication;
use core\services\Response;

class FaqBackend extends BackendApplication{
    static function getEntityClass()
    {
        return Faq::class;
    }
    public static function getApplication()
    {
        return FaqApplication::class;
    }

    public static function actionAdd($params = [])
    {
        return parent::actionMod($params); // TODO: Change the autogenerated stub
    }

    public static function actionMod($params = [])
    {
        $mod =  parent::actionMod($params); // TODO: Change the autogenerated stub


        $modLista = FaqAnswerBackend::actionComplessList([
            "params"    =>  "where/idFaq=".$mod[1]["data"]->id,
            "routeParams"  =>  [
                "idFaq" =>  $mod[1]["data"]->id
            ]
        ]);



        return[
            "tabs",[
                "tabs"=>[
                    "info"=>[
                        "label"     =>  "Info",
                        "content"   => BackendTemplate::renderTemplate($mod[0],$mod[1])
                    ],
                    "lista"=>[
                        "label"     =>  "Domande / risposte",
                        "content"   => BackendTemplate::renderTemplate($modLista[0],$modLista[1])
                    ],
                ]
            ]
        ];
    }

    static function getIcon($method = "")
    {
        return "question-circle";
    }

}