<?php

namespace applications\ecommerce\entities;


use core\db\Field;
use core\Model;
use core\services\Db;

class Prodotto extends Model{
    static function getTable()
    {
        return "ecommerce_prodotto";
    }

    static function schema()
    {
        return [
            "id"    =>  Field::primaryIndex(),
            "nome"  =>  Field::varchar(256)->editable(),
            "slug"  =>  Field::varchar(64)->editable()->setTemplate("slug")->setTemplateVar("nome"),
            "sku"  =>  Field::varchar(512)->editable(),
            "descrizione"   =>  Field::text()->editable()->setTemplate("textarea"),
            "id_ecommerce_tipologia_prodotto"   =>  Field::int()->editable(true)->setTemplate("select")->setTemplateVar(\applications\ecommerce\TipologiaProdotto::getForSelect())
        ];
    }

    static function getInstance($data)
    {
        $instance = parent::getInstance($data); // TODO: Change the autogenerated stub

        $instance->tipologia = TipologiaProdotto::findById($instance->id_ecommerce_tipologia_prodotto);
        $instance->tipologia->getFields();

        $sql = "SELECT * FROM ecommerce_prodotto_campi WHERE id_ecommerce_prodotto=:id";
        $r = Db::$connection->fetchAll($sql,[
            "id"    =>  $instance->id
        ]);

        $instance->valoriCampi = [];
        foreach ($r as $item){
            $instance->valoriCampi[$item['slug']] = $item;
        }

        $instance->varianti = $instance->getVariants();
        return $instance;
    }


    public function expand(){

    }


    public function getVariants(){
        $varianti = Variante::findById_prodotto($this->id);

        foreach ($varianti as $key=>$value){
            $value->expand();

        }
        return $varianti;
    }

}