<?php
namespace applications\menu;


use applications\schematics\entities\Schematics;
use applications\banner\entities\Banner;
use applications\banner\BannerBackend;
use applications\menu\entities\Menu;
use applications\menu\entities\MenuItem;
use applications\pages\entities\Pagina;
use core\abstracts\Application;
use core\Model;
use core\services\Response;
use core\services\RouterService;

class MenuApplication extends Application {

    static function init($n)
    {
        parent::init($n); // TODO: Change the autogenerated stub
        Response::addVariable([
            "menu"  =>  [
                "gestionecontenuti" => [[
                    "label" =>  "Menu",
                    "icon"  =>  "bars",
                    "children"  =>  [
                        ["label" => "Lista", "href" =>  "/backend/menu/lista"],
                        ["label" => "Aggiungi","href" =>  "/backend/menu/aggiungi"]
                    ]
                ]]
            ]
        ]);

        //RouterService::addRoutes(MenuItem::generateRoutes(MenuItem::class,"/backend/menuitem/"));

        RouterService::addRoutesPrefixed(MenuItemBackend::declareRoutes(),"/backend/menuitem/");



        $menu = Menu::query()->where("active=1")->getAll();

        foreach ($menu as $m){
            Response::addVariable([
                "frontend" => [
                    "menu" => [
                        $m->position=>$m
                    ]
                ]
            ]);
        }

    }

    static function getFrontendApplication()
    {
        // TODO: Implement getFrontendApplication() method.

        return null;
    }

    static function getBackendApplication()
    {
        // TODO: Implement getBackendApplication() method.
        return MenuBackend::class;
    }

    static function getEntityClass()
    {
        return Menu::class;
    }

}