<?php
/**
 * Created by PhpStorm.
 * User: phome
 * Date: 22/05/2018
 * Time: 20:55
 */

namespace applications\menu;
use applications\banner\BannerApplication;
use core\abstracts\Application;
use core\services\Response;

class MenuBackend extends \core\abstracts\BackendApplication{
    static function getApplication()
    {
        return MenuApplication::class;
    }

    static function actionMod($params = [])
    {
        $r = parent::actionMod($params); // TODO: Change the autogenerated stub

        $r[0] = "menu/templates/menu.edit";



        return $r;
    }



    static function actionList( $params = [] ){
        $entity = static::getEntityClass();


        $query=$entity::query()->where("id_menu IS NULL");
        $data = $query->getAll();



        Response::addVariable(
            [
                "title"         =>  "Prova",
                "breadcrumbs"   =>  [
                    ["link"=>"qwe","label"=>"qwe"]
                ]
            ]
        );

        return [
            "list",[
                "data"      => $data,
                "entity"    =>  $entity
            ]
        ];
    }

}