<?php

namespace frontend\consorzioleonardo\applications\ricerche;

use core\abstracts\Application;
use core\services\Response;
use frontend\consorzioleonardo\applications\imprese\entities\Impresa;
use frontend\consorzioleonardo\applications\ricerche\entities\Ricerca;


class RicercheApplication extends Application{
    static function getFrontendApplication()
    {
        return null;
    }

    static function getBackendApplication()
    {
        return RicercheBackend::class;
    }

    static function getEntityClass()
    {
        return Ricerca::class;
    }

    static function init($n)
    {
        parent::init($n); // TODO: Change the autogenerated stub


        parent::init($n); // TODO: Change the autogenerated stub
        Response::addVariable([
            "menu"  =>  [
                "gestionecontenuti" => [[
                    "icon"=>"magnifier",
                    "label" =>  "Ricerche",
                    "children"  =>  [
                        ["label" => "Ricerche", "href" =>  "/backend/ricerche/home"],
                        ["label" => "Lista", "href" =>  "/backend/ricerche/lista"],
                        ["label" => "Aggiungi","href" =>  "/backend/ricerche/aggiungi"]
                    ]
                ]]
            ]
        ]);

    }


}