<?php

namespace frontend\consorzioleonardo;

use core\services\Request;
use core\template\TwigTemplate;

class ConsorzioLeonardoTemplate extends TwigTemplate {
    function getTemplatesDirectory()
    {
        return __DIR__."/template";
    }

    static function getBaseDirectory()
    {
        return __DIR__;
    }

    public function render()
    {


        $this->response["params"] = Request::getParams();

        return parent::render(); // TODO: Change the autogenerated stub
    }


}