<?php
namespace applications\banner;


use applications\banner\entities\Banner;
use applications\banner\BannerBackend;
use applications\pages\entities\Pagina;
use core\abstracts\Application;
use core\Model;
use core\services\Response;

class BannerApplication extends Application {

    static function init($n)
    {
        parent::init($n); // TODO: Change the autogenerated stub
        Response::addVariable([
            "menu"  =>  [
                "gestionecontenuti" => [[
                    "label" =>  "Banner",
                    "children"  =>  [
                        ["label" => "Lista", "href" =>  "/backend/banner/lista"],
                        ["label" => "Aggiungi","href" =>  "/backend/banner/aggiungi"]
                    ]
                ]]
            ]
        ]);


    }

    static function getFrontendApplication()
    {
        // TODO: Implement getFrontendApplication() method.

        return null;
    }

    static function getBackendApplication()
    {
        // TODO: Implement getBackendApplication() method.
        return BannerBackend::class;
    }

    static function getEntityClass()
    {
        return Banner::class;
    }

}