<?php
namespace applications\utilities;


use backend\Menu;
use core\abstracts\Application;
use core\abstracts\BackendApplication;
use core\abstracts\FrontendApplication;
use core\Model;
use core\services\Response;
use core\services\RouterService;

class UtilitiesApplication extends Application{

    static function init($n)
    {
        parent::init($n); // TODO: Change the autogenerated stub



        $menu = new Menu("Strumenti di sistema","diamond");
        $menu->addItem("FTP",RouterService::getRoute("backend.utilities.ftp"));
        $menu->addItem("Php My Admin",RouterService::getRoute("backend.utilities.phpmyadmin"));
        $backend = Response::getBackendTemplate();
        $backend::addMenu($menu,10);
        unset($menu);


    }


    static function getFrontendApplication()
    {
     return null;
    }

    static function getBackendApplication()
    {
        return UtilitiesBackend::class;
    }

    static function getEntityClass()
    {
        return null;
    }

}