<?php
/**
 * Created by PhpStorm.
 * User: phome
 * Date: 22/05/2018
 * Time: 20:55
 */

namespace applications\users;
use applications\banner\BannerApplication;
use applications\login\LoginApplication;
use core\abstracts\Application;
use core\services\Response;

class UsersBackend extends \core\abstracts\BackendApplication{
    static function getApplication()
    {
        return UsersApplication::class;
    }




    static function actionAdd($params = [])
    {

        $m = parent::actionAdd($params); // TODO: Change the autogenerated stub
        $m[1]["additional_fields"] = '<div class="form-group">
            <label for="company" class=" form-control-label">Password
            <br><small></small>
            </label>
        
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1"><i class="fa fa-font"></i></span>
                </div>
                <input type="password" placeholder="Inserisci la password" class="form-control" name="password" value="">
            </div>
        </div>';
        $m[1]['title'] = "Inserisci nuovo Utente";

        return $m;
    }

    static function actionInsert($params = [], $data = null)
    {


        $data['password'] = LoginApplication::generateHash($data['password']);

        return parent::actionInsert($params, $data); // TODO: Change the autogenerated stub
    }

    public static function actionMod($params = [])
    {
        $m = parent::actionMod($params); // TODO: Change the autogenerated stub
        $m[1]['title'] = "Modifica Utente: ". $m[1]["data"]->nome . " " . $m[1]["data"]->cognome ;
        return $m;
    }
    public static function actionList($params = [])
    {
        $m = parent::actionList($params); // TODO: Change the autogenerated stub
        $m[1]['title'] = "Elenco Utenti";
        return $m;
    }

    static function getDescription( $method ="")
    {
        return "Gestisci gli utenti che possono accedere all'area amministrazione del sito. Puoi assegnare diversi ruoli e e gestire i permessi per il singolo utente.";
    }

    static function getTitle( $method ="")
    {
        return "Gestione utenti";
    }

    static function getIcon( $method ="")
    {
        return "users";
    }

}