<?php
namespace applications\users;


use applications\banner\entities\Banner;
use applications\banner\BannerBackend;
use applications\login\entities\RolePermission;
use applications\pages\entities\Pagina;
use applications\users\entities\User;
use core\abstracts\Application;
use core\Config;
use core\Model;
use core\Route;
use core\RouteFilter;
use core\services\Response;
use core\services\RouterService;

class UsersApplication extends Application {


    static function getFrontendApplication()
    {
        return null;
    }

    static function getBackendApplication()
    {

        return UsersBackend::class;
    }

    static function getEntityClass()
    {
        return \applications\login\entities\User::class;
    }


    static function install()
    {
        return [
            self::getEntityClass()
        ];
    }

    static function init($n)
    {
        parent::init($n); // TODO: Change the autogenerated stub



        RouterService::addRoutesPrefixed(UserRolesBackend::declareRoutes(),"/backend/users/ruoli/");
        RouterService::addFilter( (new RouteFilter())->setRegex("/backend/*")->setName("filter.permissions")->setCallback([UserRolesBackend::class,"_filterPermission"]));

        RolePermission::$permissions[] = "backend.right_aside.show";
        RolePermission::$permissions[] = "backend.right_aside.notifications.show";
        RolePermission::$permissions[] = "backend.right_aside.profile.edit.show";
        RolePermission::$permissions[] = "backend.right_aside.users";
        RolePermission::$permissions[] = "backend.right_aside.users.roles";


    }


}