<?php

namespace backend;

use core\Environment;
use core\services\Response;
use core\template\TwigTemplate;

class BackendTemplate extends TwigTemplate {
    static $menu = [];


    function getTemplatesDirectory()
    {

        $r = [ __DIR__."/template"];
        if( file_exists( Response::getFrontendTemplate()::getBaseDirectory()."/frontend/spagnesi/applications"))
            $r[] =  Response::getFrontendTemplate()::getBaseDirectory()."/frontend/spagnesi/applications";

        if( file_exists( Response::getFrontendTemplate()::getBaseDirectory()."/frontend/spagnesi/template"))
            $r[] =  Response::getFrontendTemplate()::getBaseDirectory()."/frontend/spagnesi/template";

        return $r;
    }

    static function getBaseDirectory()
    {
        return __DIR__;
    }


    static function addMenu( $menu){
        static::$menu[] = $menu;
    }

    public function render()
    {


        if( isset($this->response['data']) ){
            if(is_array($this->response['data']) && isset($this->response['data']['type']) && $this->response['data']['type'] == 'redirect'){
                Response::go($this->response['data']['to']);
                exit;
            }
        }



        $this->response['backend_menu'] = [];

        foreach (static::$menu as $menu){
            $this->response['backend_menu'][] = $menu;
        }


        return parent::render(); // TODO: Change the autogenerated stub
    }


}