<?php

namespace backend;

use core\Environment;
use core\services\Response;
use core\template\TwigTemplate;

class BackendTemplate extends TwigTemplate {
    static $menu = [];


    function getTemplatesDirectory()
    {
        return [
            __DIR__."/template",
            Environment::$ROOT."/frontend/spagnesi/applications",
            Environment::$ROOT."/frontend/spagnesi/template"
        ];
    }

    static function getBaseDirectory()
    {
        return __DIR__;
    }


    static function addMenu( $menu){
        static::$menu[] = $menu;
    }

    public function render()
    {

        $this->response['backend_menu'] = [];

        foreach (static::$menu as $menu){
            $this->response['backend_menu'][] = $menu;
        }


        return parent::render(); // TODO: Change the autogenerated stub
    }


}