<?php
namespace applications\reports;

use applications\reports\applicazioni\BolletteBackend;

use applications\reports\entities\Bolletta;


use applications\pages\entities\Pagina;
use applications\reports\entities\Consumo;
use applications\reports\entities\EnergiaErogata;
use applications\reports\entities\Fattura;
use backend\Menu;
use core\abstracts\Application;
use core\Config;
use core\Model;
use core\Route;
use core\services\Response;
use core\services\RouterService;



class ReportsApplication extends Application {

    static $config = [];

    static function init($n)
    {
        parent::init($n); // TODO: Change the autogenerated stub

        FiltriQuery::init();


        $menu = new Menu("Gestione Documenti","diamond");
        $menu->addItem("Bollette",RouterService::getRoute(Bolletta::getEntity().".list"));
        $backend = Response::getBackendTemplate();
        $backend::addMenu($menu);
        unset($menu);


    }

    static function install()
    {

        return [
            Bolletta::class,
            Consumo::class,
            EnergiaErogata::class,
            Fattura::class
        ];
    }


    static function declareRoutes()
    {

        RouterService::addRoutesPrefixed(BolletteBackend::declareRoutes(),"/backend/bollette/");

        return [];

    }



    static function getFrontendApplication()
    {
        return null;
    }

    static function getBackendApplication()
    {
        return null;

        //ReportsBackend::class;
        // return null;
    }

    static function getEntityClass()
    {
        return null;
    }

}