<?php

namespace frontend\consorzioleonardo\applications\imprese\entities;


use core\db\Field;
use core\Model;
use frontend\consorzioleonardo\applications\progetti\entities\AziendaProgetto;
use frontend\consorzioleonardo\applications\progetti\entities\Progetto;

class Impresa extends Model{
    static function schema()
    {
       return [
           "id" =>  Field::primaryIndex(),
           "nome"   =>  Field::varchar(512)->editable()->setLabel("Nome impresa"),
           "deleted"    =>  Field::boolean()->setDefault(0)
       ];
    }

    static function getDescription()
    {
        return "Gestisci le imprese collegate al CRM.";
    }

    function remove()
    {
       $this->deleted = 1;
       $this->save();
       return true;
    }


    public function expand()
    {
        parent::expand(); // TODO: Change the autogenerated stub
        $this->risposte = AziendaProgetto::query()->where("azienda_id=".$this->id)->getAll();

        AziendaProgetto::expandArray($this->risposte);
    }

    function insert()
    {

        parent::insert();
        if(isset($this->aggiungiaiprogetti)){
            $progetti = Progetto::findActive();

            foreach ($progetti as $key => $value ){
                $aziendaprogetto = new AziendaProgetto([
                    "azienda_id"    =>  $this->id,
                    "progetto_id"   =>  $value->id,
                    "risposta"  =>  AziendaProgetto::RISPOSTA_NON_RISPOSTO
                ]);

                $aziendaprogetto->save();
            }
        }
    }

}