<?php

namespace applications\ecommerce\entities;


use core\db\Field;
use core\Model;
use core\services\Response;
use core\services\RouterService;

class Categoria extends Model{
    static function getTable()
    {
        return "ecommerce_categoria";
    }

    static function schema()
    {
        return [
            "id"    =>  Field::primaryIndex(),
            "nome"  =>  Field::varchar(256)->editable(),
            "slug"  =>  Field::varchar(64)->editable()->setTemplate("slug")->setTemplateVar("nome"),
            "descrizione"   =>  Field::text()->editable()->setTemplate("textarea"),
            "padre"         =>  Field::int()->setDefault(-1)
        ];
    }

    /*
    static function actionMod($params = [])
    {
        $d = parent::actionMod($params); // TODO: Change the autogenerated stub

        return[
            "tabs", [
                "tabs" =>[
                    "proprieta" => [
                        "label" =>  "Proprietà",
                        "content"   =>  Response::getTemplateToUse("mod",$d[1],"empty.twig")->render()
                    ],
                    "immagini"  =>  [
                        "label" =>  "Immagini",
                        "content"   =>  Response::getTemplateToUse("ecommerce/templates/addimages",[
                            "directory" => "catalogo/varianti/",
                            "postRoute" =>  RouterService::getRoute(Variante::getEntity()."addimages")->build(["id"=>$d[1]['data']->id]),
                            "immagini" =>  $d[1]['data']->getImages()

                        ],"empty.twig")->render()

                    ]
                ]
            ]
        ];
    }
    */


}