<?php

namespace applications\ecommerce\entities;


use applications\media\entities\AttachmentText;
use core\db\Field;
use core\Model;
use core\Route;
use core\services\Db;
use core\services\Response;
use core\services\RouterService;

class Categoria extends Model{
    static function getTable()
    {
        return "ecommerce_categoria";
    }

    static function schema()
    {
        return array_merge([
            "id"    =>  Field::primaryIndex(),
            "nome"  =>  Field::varchar(256)->editable()->setHint("Nome della categoria, viene visualizzato nei menù e sul sito"),
            "slogan"         =>  Field::varchar(1024)->editable(),
            "slug"  =>  Field::varchar(64)->editable()->setTemplate("slug")->setTemplateVar("nome")->index(),
            "descrizione"   =>  Field::text()->editable()->setTemplate("textarea"),
            "padre"         =>  Field::int()->editable()->setDefault(-1)->setTemplate("select")->setTemplateVar(function(){
                return Categoria::getForSelect("nome","id")();
            })->index(),
            "immagine"  =>  Field::text()->editable()->setTemplate("media"),
            "custom_layout" =>  Field::text()->editable()
        ],parent::schema());
    }



    public function getImages(){
        $sql =  "SELECT * FROM ecommerce_categoria_immagine WHERE id_categoria=:id_categoria";

        return Db::$connection->fetchAll($sql,[
            "id_categoria"   =>  $this->id
        ]);
    }

    public function getUrl(){

        if( $this->padre == -1 || empty($this->padre) ) {


            return RouterService::getRoute("frontend.ecommerce.categoria")->build([
                "slug" => $this->slug
            ]);
        }else{
            //$padre = Categoria::query()->where("id=".$this->padre)->getOne();

            $padre = Categoria::findById($this->padre);


            if( !$padre ) return "";
            return RouterService::getRoute("frontend.ecommerce.subcategoria")->build([
                "father"    => $padre->slug,
                "slug"      => $this->slug
            ]);
        }
    }

    function expand()
    {
        parent::expand(); // TODO: Change the autogenerated stub

        $this->subCategories = Categoria::query(true)->where("padre=".$this->id)->getAll();


        $this->productCount = CategoriaProdotto::query(true)
            ->where("id_categoria=".$this->id)->count();

        $this->father = $this->getFather();

        Categoria::expandArray($this->subCategories);
    }


    function getFather(){

        if( $this->padre > 0 ){


            return Categoria::query(true)
                ->where("id=".$this->padre)->getOne();
        }
        return false;
    }



}