<?php
namespace applications\ecommerce\entities;


use core\db\Field;
use core\Model;

class ClienteFatturazione extends ClienteSpedizione {
    static function getTable()
    {
        return "ecommerce_cliente_fatturazione";
    }

    static function schema()
    {
        return array_merge(parent::schema(),[
            "id_spedizione" => Field::int()
        ]); // TODO: Change the autogenerated stub
    }


    function formatToString()
    {
        if( $this->id_spedizione ){
            return ClienteSpedizione::query()->where("id=".$this->id_spedizione)->getOne()->formatToString();
        }else {
            return parent::formatToString(); // TODO: Change the autogenerated stub
        }
    }
}