<?php
namespace applications\ecommerce\entities;

use core\db\Field;
use core\Model;

class LineItemMeta extends Model{
    static function useCache()
    {
        return false;
    }
    static function getTable()
    {
        return "ecommerce_carrello_lineitem_meta"; // TODO: Change the autogenerated stub
    }

    static function schema()
    {
        return array_merge([
            "id"    =>  Field::primaryIndex(),
            "meta_key"   =>  Field::varchar(128),
            "meta_value" =>  Field::text(),
            "price" =>  Field::float(),
            "id_lineitem"   =>  Field::int()
        ],parent::schema()); // TODO: Change the autogenerated stub
    }
}