<?php

namespace applications\pages\widgets;


use applications\main\widgets\WidgetFather;
use applications\pages\entities\Pagina;
use core\services\Response;

class WidgetPageNumber extends WidgetFather {

    public $value = 0;
    public $label = "Widget Card";
    public function render(){
        $this->count = Pagina::query()->count();
        $this->inactivePages = Pagina::query()->where("__active__=0")->count();

        echo Response::getTemplateToUse("pages/widgets/views/page_number",
            $this->toArray()
        )->render();
    }

    static function getWidgetLabel()
    {
        return "Page number"; // TODO: Change the autogenerated stub
    }

    static function getWidgetName()
    {
        return "page.number"; // TODO: Change the autogenerated stub
    }


}