<?php

namespace applications\pages\widgets;


use applications\main\widgets\WidgetCard;
use applications\main\widgets\WidgetFather;
use applications\pages\entities\Pagina;
use core\db\Field;
use core\services\Response;
use core\services\RouterService;

class WidgetAggiungiNuovaPagina extends WidgetCard {

    public $value = 0;
    public $label = "Aggiungi nuova pagina";
    public function prepareToRender(){

        $opzioniPagina = [];

        if($this->layout != "nonsettare"){
            $opzioniPagina['layout'] =  $this->layout;
        }

        $this->href = RouterService::getRoute(Pagina::getEntity().".insert")->build();


       return parent::prepareToRender();
    }

    public static function schema()
    {
        return self::mergeSchema([
            "layout" => Field::text()->editable()->setTemplate("select")->setTemplateVar([
                ["label"=>"Non settare","value"=>"nonsettare"],
                ["label"=>"Default","value"=>"default"]
            ])
        ]);
    }


    static function getTemplate(){
        return "pages/widgets/views/page_add";
    }


    static function getWidgetLabel()
    {
        return "Aggiungi pagina"; // TODO: Change the autogenerated stub
    }

    static function getWidgetName()
    {
        return "page.add"; // TODO: Change the autogenerated stub
    }


}