<?php
namespace applications\anagraficaimmobili;

use applications\anagraficaimmobili\entities\Condominio;
use applications\anagraficaimmobili\entities\Edificio;
use applications\anagraficaimmobili\entities\Fornitore;
use applications\anagraficaimmobili\entities\UnitaAbitativa;
use applications\anagraficaimmobili\widgets\WidgetInserisciCondominio;
use applications\login\LoginApplication;
use applications\main\entities\Notification;
use applications\meta\entities\Meta;
use Aura\Sql\Exception;
use core\Config;
use core\Email;
use core\Route;
use core\RouteFilter;
use core\services\Db;
use core\services\EmailService;
use core\services\Request;
use core\services\Response;
use core\services\RouterService;
use core\services\SessionService;
use function MongoDB\BSON\fromJSON;


class AnagraficaImmobiliBackend extends \core\abstracts\BackendApplication{



    static function declareWidgets()
    {
        return[
            WidgetInserisciCondominio::class
        ];
    }



    static function getApplication()
    {
        return AnagraficaImmobiliApplication::class;
    }

    static function getEntityClass()
    {

        //UnitaAbitativa::query(false)->setFields("unita.*")->join(Condominio::class,"campodiunitaabitativa","campodicondominio","left - inner etc messo come costante dentro Query::JOIN_LEFT")->getAll(); // oppure getOne()
        return Condominio::class;
    }

    /*
    public static function actionAdd($params = [])
    {
        echo "aggiungi";
        exit;
    }

    public static function actionMod($params = [])
    {
        //$r =  parent::actionMod($params); // TODO: Change the autogenerated stub


        var_dump($params);
        exit;

        $r[0] = "anagraficaimmobili/templates/gestioneAnagrafiche";

        return $r;
    }
    */



}

