<?php
namespace applications\menu\entities;


use core\db\Field;
use core\Model;

class MenuItem extends Model{
    static function getTable()
    {
        return "menuitem"; // TODO: Change the autogenerated stub
    }


    static function schema()
    {
        return [
            "id" => Field::primaryIndex(),
            "id_menu"   =>  Field::int()->editable()->setTemplate("select")->setTemplateVar([Menu::class,"getForSelect"]),
            "position" => Field::int()->editable(),
            "label" =>  Field::varchar(512)->editable(),
            "link_type" =>  Field::int()->editable()->setTemplate("select")->setTemplateVar([
                ["label"=>"Url","value"=>0],
                ["label"=>"Pagina","value"=>1]
            ]),
            "link"  =>  Field::text()->editable(),
            "active"    =>  Field::int()->editable()->setTemplate("select")->setTemplateVar([
                ["label"=>"Non attivo","value"=>0],
                ["label"=>"Attivo","value"=>1]
            ])
        ];
    }

}