<?php

namespace applications\slider;


use applications\slider\entities\Slide;
use core\abstracts\BackendApplication;

class SliderBackend extends BackendApplication{
    static function getEntityClass()
    {
        return Slide::getEntity(); // TODO: Change the autogenerated stub
    }

    public static function getApplication()
    {
        return SliderApplication::class; // TODO: Change the autogenerated stub
    }

    static function getIcon($method = "")
    {
        return "film-play";
    }

}