<?php
namespace applications\slider;

use applications\slider\entities\Slide;
use applications\slider\entities\Slider;
use backend\Menu;
use core\abstracts\Application;
use core\services\Response;
use core\services\RouterService;

class SliderApplication extends Application{

    public static function init($n)
    {
        parent::init($n); // TODO: Change the autogenerated stub


        $menu = new Menu("Slider",self::getBackendApplication()::getIcon());
        $menu->addItem("Lista",RouterService::getRoute(Slide::getEntity().".list"));
        $menu->addItem("Aggiungi",RouterService::getRoute(Slide::getEntity().".add"));

        $backend = Response::getBackendTemplate();
        $backend::addMenu($menu);

        $t = Response::getFrontendTemplate();
        $t->addFunction("slider",[self::class, "renderSlider" ]);

    }

    static function getFrontendApplication()
    {
        // TODO: Implement getFrontendApplication() method.
    }

    static function getBackendApplication()
    {
       return SliderBackend::class;
    }

    static function getEntityClass()
    {
       return Slide::class;
    }


    static function renderSlider($hook){
        $slider = Slider::findByHook($hook);

        return $slider->render();
    }

}