<?php

namespace frontend\consorzioleonardo\applications\imprese;


use core\abstracts\BackendApplication;
use core\services\Response;
use frontend\consorzioleonardo\applications\progetti\entities\AziendaProgetto;


class ImpreseBackend extends BackendApplication{
    static function getApplication()
    {
        return ImpreseApplication::class;
    }

    static function actionAdd($params = [])
    {
        return parent::actionMod($params); // TODO: Change the autogenerated stub
    }

    static function actionMod($params = [])
    {
        $mod = parent::actionMod($params); // TODO: Change the autogenerated stub

        $risposte = AziendaProgetto::query()->where("azienda_id=".$mod[1]['data']->id)->getAll();

        AziendaProgetto::expandArray($risposte);
        return [
            "tabs",[
                "tabs" => [
                    "impresa"    =>  [
                        "label" =>  "Dati impresa",
                        "content"   => Response::getTemplateToUse($mod[0],array_merge($mod[1],["template_extend"=>"empty.twig"]))->render()
                    ],
                    "meta"    =>  [
                        "label" =>  "Risposte date a progetti",
                        "content"   => Response::getTemplateToUse("progetti/templates/progetto.risposteaziende",[
                            "progetto"  =>  $mod[1]['data'],
                            "template_extend"=>"empty.twig",
                            "imprese"   =>  $risposte,
                            "vista" =>  "azienda"
                        ])->render()
                    ]
                ]
            ]
        ];
    }


}