<?php

namespace frontend\consorzioleonardo\applications\imprese;

use core\abstracts\Application;
use core\services\Response;
use frontend\consorzioleonardo\applications\imprese\entities\Impresa;


class ImpreseApplication extends Application{
    static function getFrontendApplication()
    {
        return null;
    }

    static function getBackendApplication()
    {
        return ImpreseBackend::class;
    }

    static function getEntityClass()
    {
        return Impresa::class;
    }

    static function init($n)
    {
        parent::init($n); // TODO: Change the autogenerated stub


        parent::init($n); // TODO: Change the autogenerated stub
        Response::addVariable([
            "menu"  =>  [
                "gestionecontenuti" => [[
                    "icon"  =>  "apartment",
                    "label" =>  "Imprese",
                    "children"  =>  [
                        ["label" => "Lista", "href" =>  "/backend/imprese/lista"],
                        ["label" => "Aggiungi","href" =>  "/backend/imprese/aggiungi"]
                    ]
                ]]
            ]
        ]);

    }


}