<?php

namespace frontend\consorzioleonardo\applications\imprese;


use core\abstracts\BackendApplication;
use core\services\Response;
use frontend\consorzioleonardo\applications\progetti\entities\AziendaProgetto;


class ImpreseBackend extends BackendApplication{
    static function getApplication()
    {
        return ImpreseApplication::class;
    }

    static function actionAdd($params = [])
    {
        $r = parent::actionMod($params); // TODO: Change the autogenerated stub

        $r[0] = "imprese/templates/add";
        return $r;
    }

    static function actionInsert($params = [], $data = null)
    {
        $r = parent::actionInsert($params, $data); // TODO: Change the autogenerated stub



        return $r;
    }


    static function actionMod($params = [])
    {
        $mod = parent::actionMod($params); // TODO: Change the autogenerated stub

        $risposte = AziendaProgetto::query()->where("azienda_id=".$mod[1]['data']->id)->getAll();

        AziendaProgetto::expandArray($risposte);
        return [
            "tabs",[
                "tabs" => [
                    "impresa"    =>  [
                        "label" =>  "Dati impresa",
                        "content"   => Response::getTemplateToUse($mod[0],array_merge($mod[1],["template_extend"=>"empty.twig"]))->render()
                    ],
                    "meta"    =>  [
                        "label" =>  "Risposte date a progetti",
                        "content"   => Response::getTemplateToUse("progetti/templates/progetto.risposteaziende",[
                            "progetto"  =>  $mod[1]['data'],
                            "template_extend"=>"empty.twig",
                            "imprese"   =>  $risposte,
                            "vista" =>  "azienda"
                        ])->render()
                    ]
                ]
            ]
        ];
    }


    static function actionList( $params = [] ){
        $entity = static::getEntityClass();
        $data = $entity::query()->where("deleted=0")->getAll();

        Response::addVariable(
            [
                "title"         =>  "Lista ".$entity::getEntityName(),
                "breadcrumbs"   =>  [
                    ["link"=>"qwe","label"=>"qwe"]
                ],
                "application_info"  =>  [
                    "icon"   =>  static::getIcon("actionMod"),
                    "title"   =>  static::getTitle("actionList"),
                    "description"   =>  static::getDescription("actionList")
                ]
            ]
        );

        return [
            "list",[
                "data"      => $data,
                "entity"    =>  $entity,
                "fields"    =>  $entity::schema()
            ]
        ];
    }


}