<?php

namespace applications\reports\entities;


use applications\anagraficaimmobili\entities\UnitaAbitativa;
use core\db\Field;
use core\Model;
use core\services\Db;

use applications\anagraficaimmobili\entities\Condominio;
use applications\anagraficaimmobili\entities\TipoAggregatore;


class Fattura extends Model{

    static function schema()
    {
        return [
            "id"    =>  Field::primaryIndex(),
            "idBolletta"    =>  Field::int(),
            "idUnitaAbitativa" =>  Field::int(),
            "pdf"    =>  Field::varchar(512),
            "data_generazione"  =>  Field::date(),
            "totale"    =>  Field::float()
        ];
    }

    static function getInstance($data)
    {

        $instance = parent::getInstance($data); // TODO: Change the autogenerated stub
        $instance->unitaAbitativa = UnitaAbitativa::findById($instance->idUnitaAbitativa);
        return $instance;
    }

}


