<?php
namespace applications\schematics;


use applications\schematics\entities\Schematics;
use applications\schematics\SchematicsBackend;
use applications\pages\entities\Pagina;
use core\abstracts\Application;
use core\Model;
use core\services\Response;
use core\services\RouterService;

class SchematicsApplication extends Application {

    static function init($n)
    {
        parent::init($n); // TODO: Change the autogenerated stub
        /*Response::addVariable([
            "menu"  =>  [
                "gestionecontenuti" => [[
                    "label" =>  "Schematics",
                    "children"  =>  [
                        ["label" => "Lista", "href" =>  "/backend/schematics/lista"],
                        ["label" => "Aggiungi","href" =>  "/backend/schematics/aggiungi"]
                    ]
                ]]
            ]
        ]);*/

        $menu = new \backend\Menu("Schematics","cog");
        $menu->addItem("Lista",RouterService::getRoute(Schematics::getEntity().".list"));
        $menu->addItem("Aggiungi",RouterService::getRoute(Schematics::getEntity().".add"));
        $backend = Response::getBackendTemplate();
        $backend::addMenu($menu);



    }

    static function getFrontendApplication()
    {
        // TODO: Implement getFrontendApplication() method.

        return null;
    }

    static function getBackendApplication()
    {
        // TODO: Implement getBackendApplication() method.
        return SchematicsBackend::class;
    }

    static function getEntityClass()
    {
        return Schematics::class;
    }

}