<?php
/**
 * Created by PhpStorm.
 * User: phome
 * Date: 22/05/2018
 * Time: 20:55
 */

namespace applications\meta;
use core\abstracts\Application;

class MetaBackend extends \core\abstracts\BackendApplication{
    static function getApplication()
    {
        return MetaApplication::class;
    }

    static function actionMod($params = [])
    {

        return parent::actionMod($params); // TODO: Change the autogenerated stub
    }

}