<?php

namespace frontend\consorzioleonardo\applications\ricerche\templates\ricerche;


use frontend\consorzioleonardo\applications\imprese\entities\Impresa;

class ImpresaTemplate extends RicercaTemplate {
    function render()
    {


        foreach ($this->risultati as $value){
            /**
             * @var $value Impresa
             */
            $value->expand();
        }
        $r =  parent::render(); // TODO: Change the autogenerated stub


        $r[0] = "ricerche/templates/ricerche/impresa";
        return $r;
    }
}