<?php
namespace frontend\spagnesi\applications\homepage;

use core\abstracts\BackendApplication;
use core\abstracts\FrontendApplication;
use core\Model;
use core\services\Response;

class HomepageApplication extends \core\abstracts\Application {


    static function init($n)
    {
        parent::init($n); // TODO: Change the autogenerated stub
        Response::addVariable([
            "menu"  =>  [
                "gestionecontenuti" => [[
                    "label" =>  "Homepage",
                    "children"  =>  [
                        ["label" => "Gestisci", "href" =>  "/backend/".static::$name."/gestisci"],

                    ]
                ]
                ]]
        ]);
    }

    static function getFrontendApplication()
    {
        return HomepageFrontend::class;
    }

    static function getBackendApplication()
    {
        return HomepageBackend::class;
    }

    static function getEntityClass()
    {
        // TODO: Implement getEntityClass() method.
    }

}