<?php

namespace applications\ecommerce;

use applications\ecommerce\entities\Carrello;
use applications\ecommerce\entities\LineItem;
use applications\ecommerce\entities\Ordine;
use backend\BackendTemplate;
use core\abstracts\Application;
use core\abstracts\BackendApplication;
use core\Email;
use core\Route;
use core\services\RouterService;

class Ordini extends BackendApplication {
    static function getApplication()
    {
        return EcommerceApplication::class;
    }

    static function ordini(){

        return [
            "ecommerce/templates/ordini",[]
        ];
    }

    static function getEntityClass()
    {
        return Ordine::class;
    }


    static function declareRoutes()
    {
        return array_merge(
            parent::declareRoutes(),[
            "backend.ordini.mailriepilogointerno"  =>  new Route("",Ordine::getModLink()."/mail-riepilogo-interno",[static::class,"_mailRiepilogoInterno"])
        ]);
    }

    static function _mailRiepilogoInterno($params =[]){

        $ordine = Ordine::findById($params['id']);


        $email = new Email();
        $email->from= "info";
        $email->to= "info";
        $email->template = "conferma-ordine-interno";
        $email->subject ="Copia conferma ordine ".$ordine->getNumeroOrdine();



        $email->setData([
            "ordine"  =>  $ordine,
            "lineitems" =>  $ordine->carrello->lineitems
        ]);
        $email->data['numeroordine'] = $ordine->getNumeroOrdine();
        $email->send();
        exit;
    }
    static function _previewEmail($params = []){


        $email = new Email();
        $email->from= "info";
        $email->to= "phomea@gmail.com";
        $email->template = $params['nome'];
        $email->subject ="Conferma ordine";

        $email->setData($params);
        $email->bindData();

        echo $email->message;


        exit;
    }


    static function actionMod($params = [])
    {
        $mod = parent::actionMod($params); // TODO: Change the autogenerated stub
        $ordine = $mod[1]['data'];


        $mod[1]["bottomButtons"] = [
            [
                "url"   =>  RouterService::getRoute("backend.ordini.mailriepilogointerno")->build([
                    "id"=> $ordine->id
                ]),
                "text"  =>  "Invia di nuovo la mail interna per riepilogo"
            ]
        ];

        $lineitems = LineItems::actionComplessList([
            "params"    =>  "/join/ecommerce_carrello on ecommerce_carrello.id=ecommerce_carrello_lineitem.id_carrello/join/ecommerce_ordine on ecommerce_ordine.id_carrello=ecommerce_carrello.id/where/ecommerce_ordine.id=".$ordine->id,
            "routeParams"   =>[
                "id_ordine"     =>  $ordine->id
            ]
        ]);

        /*
        $lineitems = LineItems::actionComplessList([
            "params"    =>  "/where/ecommerce_ordine.id=".$ordine->id."/join/ecommerce_carrello on ecommerce_carrello.id=ecommerce_carrello_lineitem.id_carrello/join/ecommerce_ordine on ecommerce_ordine.id=ecommerce_carrello.order_id",
            "routeParams"   =>[
                "id_ordine"     =>  $ordine->id
            ]
        ]);*/


        $pagamenti = Pagamenti::actionComplessList([
            "params"    =>  "/where/id_ordine=".$ordine->id,
            "routeParams"   =>[
                "id_ordine"     =>  $ordine->id
            ]
        ]);



        return[
            "tabs" ,[
                "tabs"=>[
                    BackendTemplate::renderTemplateSingleTab("Ordine",$mod[0],$mod[1]),
                    BackendTemplate::renderTemplateSingleTab("Pagamenti",$pagamenti[0],$pagamenti[1]),
                    BackendTemplate::renderTemplateSingleTab("Oggetti nel carrello",$lineitems[0],$lineitems[1])
                ]
            ]
        ];
    }

}