<?php

namespace applications\ecommerce;

use applications\ecommerce\entities\Pagamento;
use core\abstracts\BackendApplication;

class Pagamenti extends BackendApplication{
    static function getEntityClass()
    {
        return Pagamento::class; // TODO: Change the autogenerated stub
    }

    static function getApplication()
    {
        return EcommerceApplication::class; // TODO: Change the autogenerated stub
    }
}