<?php

namespace applications\ecommerce;

use applications\ecommerce\entities\Ordine;
use applications\ecommerce\entities\Variante;
use Braintree\AccountUpdaterDailyReport;
use core\abstracts\Application;
use core\abstracts\BackendApplication;
use core\Route;
use core\services\Db;
use core\services\Response;
use core\services\RouterService;

class Varianti extends BackendApplication {
    static function getApplication()
    {
        return EcommerceApplication::class;
    }

    static function declareRoutes()
    {
        $r = parent::declareRoutes(); // TODO: Change the autogenerated stub

        $r[Variante::getEntity()."addimages"] = (new Route(Variante::getEntity().".addimages","{id:([0-9]*)}/addimages",[self::class,"addImages"]))->method(Route::METHOD_POST);

        return $r;
    }


    static function getEntityClass()
    {
        return Variante::class;
    }

    static function actionAdd($params = [])
    {
        $d = parent::actionMod($params); // TODO: Change the autogenerated stub


        $variante = $d[1]["data"];


        return[
            "tabs", [
                "tabs" =>[
                    "proprieta" => [
                        "label" =>  "Proprietà",
                        "content"   =>  Response::getTemplateToUse("mod",$d[1],"empty.twig")->render()
                    ]
                ]
            ]
        ];
    }

    static function actionMod($params = [])
    {
        $d = parent::actionMod($params); // TODO: Change the autogenerated stub


        $variante = $d[1]["data"];
        $prodotto = $variante->getProduct();
        $variante->expand();

        $attributiTipologia = $prodotto->tipologia->getAttributes();
        return[
            "tabs", [
                "tabs" =>[
                    "proprieta" => [
                        "label" =>  "Proprietà",
                        "content"   =>  Response::getTemplateToUse("mod",$d[1],"empty.twig")->render()
                    ],
                    "attributi" =>[
                        "label" =>  "Attributi",
                        "content"   =>  Response::getTemplateToUse("ecommerce/templates/variante.edit.attributi",[
                            "prodotto"=>$prodotto,
                            "variante"  =>  $variante,
                            "attributiTipologia"=>$attributiTipologia
                        ])->render()
                    ]
                ]
            ]
        ];
    }

    static function addImages( $params =[], $data ){




        $sql = "INSERT INTO ecommerce_prodotto_variante_immagine (id_variante,permalink) VALUES (:id,:permalink)";

        Db::$connection->perform($sql,[
            "id" => $params['id'],
            "permalink" => $data['permalink']
        ]);


        $lastid = Db::$connection->lastInsertId();

        $sql = "SELECT * FROM ecommerce_prodotto_variante_immagine where id=:id";
        return ["",[
            "data"=>Db::$connection->fetchOne($sql,["id"=>$lastid])
        ]
        ];

        var_dump($data);
        exit;
    }


}